### ISSUE TITLE
lost/precss etc only work in style.css but in none of the other css files

### ISSUE THREAD

**Issue by HarrisRobin** [christiansakai/overreact#1]
As the title says. for now i am doing all the styling in style.css since it works there. Need to investigate.

**Comment by HarrisRobin** [comment]
On top of this, if i dont refresh style.css then the styles do not apply on the fly. I have to go in style.css in save it.

**Comment by christiansakai** [comment]
Ok, fixed it.
1. CSS refresh on the fly
2. Lost usable in any css
